### ISSUE TITLE
As a dev I want to have a ErrNone object to encapsulate the nil value

### ISSUE THREAD

**Issue by 6l20** [ConsenSys/quorum-key-manager#139]
The idea behind having an ErrNone object is to avoid this kind of statement

```
if err != nil && errors.IsNotSupportedError(err) {
   return
}
```
where the caller has the responsability of testing the nullity of err

And to also avoid having a call on a nil receiver with this statement

```
if errors.IsNotSupportedError(err) {
   return
}
```

Below is an example of what the FrmError function could be :

```
func FromError(err interface{}) *Error {
   if err == nil {
      // now return ErrNone instead of nil
      return ErrNone
   }
   ierr, ok := err.(*Error)
   if !ok {
      return Errorf(Internal, err.(error).Error())
   }
   return ierr
}
```

**Comment by dolanor** [comment]
What would this ErrNone represent? That there is no error?
