### ISSUE TITLE
Create alias service "backend" allowing to perform CRUD operations for aliases

### ISSUE THREAD

**Issue by nmvalera** [ConsenSys/quorum-key-manager#146]
#### Summary

Create backend to store aliases to database

- An alias is attached to one and only one registry
- An alias holds a value which can be any JSON object or an array
- Each alias as a type (in string format) passed by the users

#### Acceptance Criteria

- [ ] Create Postgres database schema
- [ ] Add migration scripts for the database
- [ ] Add configuration flags for the database
- [ ] Add method to create and store an alias
- [ ] Add method to load an alias
- [ ] Add method to delete an alias
- [ ] Add method to list aliases attached to a registry
- [ ] Add method to update an alias
- [ ] Add unit-test

**Comment by dolanor** [comment]
> - An alias holds a value which can be any JSON object or an array

Which form would that take exactly?

**Comment by dolanor** [comment]
Replying to myself, it's available [here](https://docs.google.com/document/d/1cgfbBb7EJ-CAvkR21k0h4GdEC_vS1XdMrEg-PIPvaak/edit#)
```
POST /registries/my-registry/aliases/group-A
{
       “type”: “array”, 
       “value”:[
“ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc=”,
”2T7xkjblN568N1QmPeElTjoeoNT4tkWYOJYxSMDO5i0=”
]
}
```
