### ISSUE TITLE
Implement API allowing to manage aliases

### ISSUE THREAD

**Issue by nmvalera** [ConsenSys/quorum-key-manager#147]
#### Summary

Implement API for alias service allow to manage aliases

#### Acceptance criteria

- [ ] Add `POST /registries/{name}/aliases/{alias}`
- [ ] Add `GET /registries/{name}/aliases/{alias}`
- [ ] Add `DELETE /registries/{name}/aliases/{alias}`
- [ ] Add `PATCH /registries/{name}/aliases/{alias}`
- [ ] Add `GET /registries/{name}`
- [ ] Add `DELETE /registries/{name}`
- [ ] Add an HTTP Client to access above routes
- [ ] Add Acceptance tests
- [ ] Add swagger documentation

**Comment by dolanor** [comment]
For this ticket, I think we should have:
- [ ] Add `POST /registries/{name}/aliases`: to create a new alias instead

Also, what would be the content format of the PATCH? Or do we want a `PUT` instead?

**Comment by dolanor** [comment]
> For this ticket, I think we should have:
> 
>     * [ ]  Add `POST /registries/{name}/aliases`: to create a new alias instead
Finally, it is a POST directly with the alias key in the URL
```
POST /registries/{name}/aliases/{alias_key}
```

> Also, what would be the content format of the PATCH? Or do we want a `PUT` instead?
I used a put since it is a simple replace of the value

I didn't create a HTTP Client to the route. I'll create a ticket for that.
