### ISSUE TITLE
Allow to pass alias placeholders in JSON-RPC request

### ISSUE THREAD

**Issue by nmvalera** [ConsenSys/quorum-key-manager#148]
#### Summary

Allow to next arguments pass JSON-RPC to replace
- `privateFor` c.f. https://docs.google.com/document/d/1cgfbBb7EJ-CAvkR21k0h4GdEC_vS1XdMrEg-PIPvaak/edit#heading=h.hebsvnkcovnm
- `privacyGroupId` c.f. https://docs.google.com/document/d/1cgfbBb7EJ-CAvkR21k0h4GdEC_vS1XdMrEg-PIPvaak/edit#heading=h.njkpsii4nbvo

#### Acceptance Criteria

- [x] Enable to parse alias placeholders in JSON-RPC request (the current proposal is `{{...}}`)
- [x] Allow `eth_sendTransaction` interceptor to use alias in `privateFor`
- [x] #377
- [x] #393
- [x] #388
- [x] Allow `eth_sendRawPrivateTransaction` interceptor to use alias in `privacyGroupId` argument
- [x] Allow `eea_sendTransaction` interceptor to use alias in  `privateFor`
- [x] Allow `eea_sendTransaction` interceptor to use alias in  `privacyGroupId` (in this case if the alias value is a string it should be treated as the privacy group id, if alias value is a string array then it should be treated as an array to pass in `privateFor`
- [x] Allow `eea_sendTransaction` interceptor to use alias in `privateFrom`
- [x] E2E tests for all JSON-RPC methods

**Comment by dolanor** [comment]
All the work on EEA has been merged with #421 
There is one test missing in the E2E, it is the test of the PrivacyGroupID alias pointing to a PrivacyGroupID (as a string), as opposed as a PrivacyGroupID alias pointing to an array alias. It would be good to add it to ensure completeness.
