### ISSUE TITLE
Allow to pass alias registry in HTTP header of a JSON-RPC request

### ISSUE THREAD

**Issue by nmvalera** [ConsenSys/quorum-key-manager#149]
#### Summary

c.f. https://docs.google.com/document/d/1cgfbBb7EJ-CAvkR21k0h4GdEC_vS1XdMrEg-PIPvaak/edit#heading=h.uho2cv5f06pw

#### Acceptance Criteria

- [ ] Allow JSON-RPC interceptor to extract registry name from `Alias-Registry` header (default should be `default`) It should be compatible with both `HTTP` and `WebSocket`
- [ ] E2E tests

**Comment by darioAnongba** [comment]
I'm not sure to see much value in this. Wouldn't it be better to use a prefix in the aliases ? like `{registry_name}:{alias}` ?
