### ISSUE TITLE
Allow recursive aliasing

### ISSUE THREAD

**Issue by nmvalera** [ConsenSys/quorum-key-manager#150]
#### Summary

Enable recursive aliasing (alias containing other aliases)

```
POST /registries/my-registry/aliases/group-A
{	
     "type":"[string]", 
     “value”:[
"{{/registries/my-registry/aliases/JPM}}",
"{{/registries/my-registry/aliases/GS}}"
]
```

### Acceptance criteria

- [ ] Allow storing a recursive aliases
- [ ] Allow resolving recursive aliases  
- [ ] E2E tests

**Comment by darioAnongba** [comment]
I don't see value in this feature and I consider it as over-engineered to be honest.
