### ISSUE TITLE
Add Postgres dependency

### ISSUE THREAD

**Issue by nmvalera** [ConsenSys/quorum-key-manager#161]
#### Summary

The is a technical task consisting of integrating base components to allow the development of feature requiring data management in PostgresSQL

#### Acceptance criteria

- [ ] Implement base component to connect to a Postgres DB using `go-pg` including transaction database interface, config struct, SSL dialer, etc. (see with Orchestrate)
- [ ] Create DB mock for testing
- [ ] Add Postgres docker-compose service (to be started in Makefile)
- [ ] Add pgadmin to deps
- [ ] Add Postgres to Acceptance Test Suite and implement a base test suite (creating database, creating a table, adding an entry to the table, deleting the table, deleting database)

**Comment by darioAnongba** [comment]
This has been implemented in my PRs already. Closing and linking the missing migrations ticket to be implemented:
- https://app.zenhub.com/workspaces/orchestrate-5ea70772b186e10067f57842/issues/consensys/quorum-key-manager/203
