### ISSUE TITLE
Refactor e2e and acceptance tests

### ISSUE THREAD

**Issue by julien-marchand** [ConsenSys/quorum-key-manager#163]
The following describes the scope of work for each of the test suites
```
## Acceptance
It should validate the integration of our application with external dependencies such as PG and KeyVaults. It requires access to internal application components and dependencies so we can validate edge cases such as down times over our deps.

## e2e
It should validate our application from the users point of view and guarantee each provided feature works as expected for users
```

# Acceptance criteria

### Integration (aka Acceptance)
- [x] Rename acceptance test as integrations test
- [x] Integration tests should validate connections with PG and Hashicorp, skipping AKV and KMS (as they cannot be loaded in a container)
- [x] Integration tests can be implemented by using Connectors interfaces
- [x] It should run on every branch PR
- [ ] Validate authorization, resource+action + `allowed_tenants` checks

### e2e 
- [x] It should test our application using APIs
- [ ] Validate authentication: JWT, TLS and API-Key
- [ ] **Light version of it**, using only a local instance of Hashicorp should run on every branch PR
- [x] **Full version of it**, using long living instances of Hashicorp, AKV and KMS, should run only on Master and Tags

**Comment by ggarri** [comment]
Recap over what it was discussed on Slack:

The following describes the scope of work for each of the test suites
```
## Acceptance
It should validate the integration of our application with external dependencies such as PG and KeyVaults. It requires access to internal application components and dependencies so we can validate edge cases such as down times over our deps.

## e2e
It should validate our application from the users point of view and guarantee each provided feature works as expected for users
```

The proposed changes to accomplish that are:

### Integration (aka Acceptance)
- [ ] Rename acceptance test as integrations test
- [ ] Integration tests should validate connections with PG and Hashicorp, skipping AKV and KMS (as they cannot be loaded in a container)
- [ ] Integration tests can be implemented by using Connectors interfaces
- [ ] It should run on every branch PR

### e2e 
- [ ] It should test our application using APIs
- [ ] It should validate authroization and authentication
- [ ] A light version of it, using only a local instance of Hashicorp should run on every branch PR
- [ ] a full version of it, using long living instances of Hashicorp, AKV and KMS, should run only on Master and Tags
