### ISSUE TITLE
log when no services are loaded

### ISSUE THREAD

**Issue by dolanor** [ConsenSys/quorum-key-manager#189]
It is possible to start a service that is empty. We should log it.
At the moment, it only logs what's loaded, when it's loaded. In the absence of service, we just get:
```
2021-07-05T15:36:01.044Z	INFO	app	application started
2021-07-05T15:36:01.044Z	INFO	app	started API server	{"addr": "127.0.0.1:8080"}
2021-07-05T15:36:01.044Z	INFO	app	started Health server	{"addr": "127.0.0.1:8081"}
```
Which makes you think it's working OK if it's only a few time dealing with this project.

**Comment by darioAnongba** [comment]
Being able to start a QKM without any store is not a bug. stores can be created after the QKM starts and we are planning on implementing the possibility to add stores on the fly using the API (HTTP requests). This behavior is correct at the moment.
