### ISSUE TITLE
Remove passing context everywhere it is not needed

### ISSUE THREAD

**Issue by darioAnongba** [ConsenSys/quorum-key-manager#238]
Currently, we pass the context to almost every function when we define an interface. Sometimes, this context is not used because the underlying functionality does not need it and will never need it.
The purpose of this ticket is to remove passing context when it is not used.

Examples:
- AKV infra
- AWS infra
- Hashicorp infra

**Comment by dolanor** [comment]
Actually, `context.Context` is really useful for metrics, tracing and passing metadata about a request, and of cours interrupting a request in the middle if the original request was stopped. It avoids doing expensive IO if we can avoid it.
Out of the 3 services, only Hashicorp vault doesn't handle context. But AKV infra currently use the context API from AKV, the AWS infra could use the context function, but doesn't. It should be updated.
