### ISSUE TITLE
Split Roles and Permissions in JWT/TLS/API_KEY

### ISSUE THREAD

**Issue by julien-marchand** [ConsenSys/quorum-key-manager#259]
# Description

Use a specific field for Roles and another one for Permissions

## JWT

- Use scope for Permissions
- Add property XXX for Roles

## API Key

- Use column for Permissions only
- Add columns for Roles

**Comment by ggarri** [comment]
TLS was inspired from https://kubernetes.io/docs/reference/access-authn-authz/authentication/#x509-client-certs

**Comment by 6l20** [comment]
Handling Authorization via TLS, standard elements found

The below RFC 5878 allows specific extensions introduction during Handshake

https://datatracker.ietf.org/doc/html/rfc5878

These extensions need to be negociated between client and server (supported by)

Below is an implementation proposal using DTCP certificates (Digital Transmission Content Protection)

https://tools.ietf.org/id/draft-dthakore-tls-authz-00.html

Also standardized here 

https://www.rfc-editor.org/rfc/rfc7562

Note:

This technique implies the exchange of supplemental data during the handshake as specified here https://www.rfc-editor.org/rfc/rfc4680

Note:

Golang TLS server is not compliant with this technique as far as I know, would require extensions if feasible
