### ISSUE TITLE
Fix Helm Charts & Kubernetes files

### ISSUE THREAD

**Issue by julien-marchand** [ConsenSys/quorum-key-manager#303]
# Acceptance criteria

- [x] Fix HashiCorp Vault agent
- [x] Update to the stable version of the KM
- [x] Deploy and test the remote environment on k8s with HashiCorp, AKV & AWS KMS
- [x] Review [HashiCorp deployment checklist](https://www.vaultproject.io/docs/platform/k8s/helm/run#production-deployment-checklist)

**Comment by 6l20** [comment]
About Hashicorp deployment requirements

- Immutable Upgrades (Already done with permanent volumes)
- Upgrade Frequently ( Today running vault 1.8.2, should be foreseen in the future)
- Restrict Storage Access. ( client responsibility ?) found nothing relevant that could guaranty
