### ISSUE TITLE
Create docker image with Hashicorp + plugin

### ISSUE THREAD

**Issue by ggarri** [ConsenSys/quorum-key-manager#315]
To remove the friction of running HashiCorp + Orchestrate plugin we should create self-contained images with it.

This should be done as part of the CircleCI pipeline of https://github.com/ConsenSys/orchestrate-hashicorp-vault-plugin

# Acceptance criteria

- [x] Update README of https://github.com/ConsenSys/orchestrate-hashicorp-vault-plugin (remove Orchestrate, make sure everything works)
- [x] Move "Development" to CONTRIBUTING.md
- [x] Automatically build the Docker image from HashiCorp, add the plugin. Update instruction to run in Development using the Docker image. Try to the Automated build approach based on the HashiCorp Github repository

**Comment by ricardolyn** [comment]
@ggarri @julien-marchand the issue is showing up in the GoQ board. I assume is a mistake?
