### ISSUE TITLE
Question : Is QKM support `eth_sendRawPrivateTransaction` ?

### ISSUE THREAD

**Issue by hammerstrike** [ConsenSys/quorum-key-manager#415]
Is QKM support `eth_sendRawPrivateTransaction` as well ?
Reference link : https://docs.quorum-key-manager.consensys.net/en/stable/Concepts/Nodes/

**Comment by darioAnongba** [comment]
Hi @hammerstrike, yes QKM supports every JSON-RPC call because the QKM will simply act as a proxy and forward the call to the underlying node. 

In cases where the request needs to sign with an account, the QKM intercepts the request and signs before forwarding the request to the underlying node.

**Comment by dolanor** [comment]
Actually, it is not yet implemented. We can track it in #392 .
