### ISSUE TITLE
[QKM Docker image] Support for arm64 platform - Apple M1 Silicon

### ISSUE THREAD

**Issue by jpnovais** [ConsenSys/quorum-key-manager#428]
### Summary

Create docker images compatible with `linux/arm64` platform to run QKM in Apple M1

  
### Technical Notes

Current images `linux/amd64` throw the following error:
```
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```
It looks to be due to a bug in [qemu](https://www.qemu.org/). Official docker team recommendation is to build arm64 images.
[similar issue](https://github.com/docker/for-mac/issues/5123)

I was able to create an image that could run on Apple M1 Pro (no performance or exhaustive testing) by removing the option ~~`GOARCH=amd64`~~ in the [Dockerfile](https://github.com/ConsenSys/quorum-key-manager/blob/main/Dockerfile#L22). The created in Apple M1 Pro machine as well.

## Business Value
Apple Silicon processors are becoming mainstream, specially among developers. It would be good to run this in new Apple M1 computers for development in project that use QKM as part of its stack.

### Acceptance Criteria

- [ ] Publish an image that runs on `linux/arm64` platform

**Comment by ggarri** [comment]
Hi @pedronfigueiredo 

we recently added to our CI/CD a task to build and publish arm64 compatible images. The first one of the round it is this one

https://hub.docker.com/layers/consensys/quorum-key-manager/v21.12.1-arm64/images/sha256-02cbbe1593716ce939b2bdcb5a74c7241f5c6ced7455c04c61a5e92785c018fc?context=explore
