### ISSUE TITLE
Basic Auth returns invalid api_key

### ISSUE THREAD

**Issue by hnamzian** [ConsenSys/quorum-key-manager#449]
Hey guys

I'm trying using Basic Auth and have set api key in my auth.csv file. while I'm passing Basic Auth value(that is base64 encoded of API key) through my request I always get invalid api_key. here is what I have set in my test:

API key in my csv: 06da1afe-16d3-48fe-8ec2-fea8648d737a
Auth Value through my request: MDZkYTFhZmUtMTZkMy00OGZlLThlYzItZmVhODY0OGQ3Mzdh

I wanna know what's the relation between API Key in CSV file and Auth Value in request.

**Comment by darioAnongba** [comment]
Hi @hnamzian, sorry for the delay. Here is the documentation about api keys: https://docs.quorum-key-manager.consensys.net/en/latest/HowTo/Authenticate/API-Key/

If your api key is `06da1afe-16d3-48fe-8ec2-fea8648d737a`. Then you should define it in your CSV file as `sha256(06da1afe-16d3-48fe-8ec2-fea8648d737a) = 4fb54cba957c094e0d6c66bd5c39592c19fdd8d1597651f483460593bebaa0be`

The goal is that the "real" api key is never written in the CSV file, only the sha256 of the api key in case the CSV file is exposed.
Then, on your calls, you will pass the `base64(06da1afe-16d3-48fe-8ec2-fea8648d737a) = MDZkYTFhZmUtMTZkMy00OGZlLThlYzItZmVhODY0OGQ3Mzdh`
