### ISSUE TITLE
Use only go-quorum types across the codebase

### ISSUE THREAD

**Issue by darioAnongba** [Consensys/quorum-key-manager#95]
Currently we use both go-ethereum and go-quorum imports in the codebase due to a bug in the go-quorum codebase that prevents us from importing it. The goal is to use use only go-quorum types across the codebase.

**Acceptance criteria**:
- Use only go-quorum imports
- Remove duplicated functions returned go-ethereum types.
- Update interfaces

**Comment by dolanor** [comment]
I guess the go-quorum bug was with the import of secp256k1 for licensing reasons. We removed it in https://github.com/ConsenSys/quorum/pull/1260
So normally, it should work with goquorum everywhere now.
